services:
  - type: web
    name: js-visualiser-server
    runtime: node
    plan: free
    autoDeployTrigger: "off"
    rootDir: .
    buildCommand: npm ci --include=dev && npm run build -w @jsv/server
    startCommand: npm run start -w @jsv/server
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
